name: libby_guild
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.17
  logger: ^1.1.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^13.0.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  url_launcher: ^6.1.10
  go_router: ^6.5.2
  file_picker: ^5.2.9
  js: ^0.6.2
  maps_launcher: ^2.2.0
  package_info_plus: ^3.1.0
  collection: ^1.17.0
  firebase_database: ^10.0.0
  cupertino_icons: ^1.0.6
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/png/